"""Pipeline stage implementations — Decompose, Search, Entity, DeepRead, Analyze, Quality, Output."""

from __future__ import annotations

import asyncio
import contextlib
import time
from pathlib import Path

from minerva.knowledge.store import Entity
from minerva.pipeline.engine import IPipelineStage, QualityGateFailure, ResearchContext
from minerva.shared import spacy_to_entity_type

DECOMPOSE_PROMPT = """Decompose this research question into 3-5 specific sub-questions.
Each sub-question should cover a distinct aspect. Output one question per line.
Research question: {query}"""

DEEP_READ_PROMPT = """Analyze the following documents about: {query}

For each source:
1. Extract key claims
2. Note consensus (all sources agree)
3. Note contradictions (sources disagree)
4. Note gaps (topics not covered)
5. Note evolution relationships (builds on, refutes)

Documents:
{documents}

Provide structured analysis in markdown."""

CROSS_ANALYZE_PROMPT = """Given this analysis of multiple sources about: {query}

{analysis}

Perform deep reasoning:
1. For each contradiction: which claim is more credible and why?
2. For each gap: is it unexplored or unsolvable with current methods?
3. Based on evolution patterns: what is the likely next development?
4. Assign confidence scores (HIGH/MEDIUM/LOW) to each conclusion.

Output structured reasoning in markdown."""

REPORT_TEMPLATE = """# Research Report: {query}

> **Paradigm**: {paradigm_name} | **Quality Score**: {quality_score}/100 | **Level**: {level} | **Sources**: {source_count} | **Cost**: ${cost}
>
> {paradigm_stages}

---

## Executive Summary

{tldr}

---

## Research Process

{process_log}

---

## Key Findings

{findings}

---

## Evidence Matrix

| # | Claim | Source | Confidence | Supports |
|---|-------|--------|------------|----------|
{evidence_rows}

---

## Contradictions & Disputes

{contradictions}

---

## Analysis Depth

{sub_questions_analysis}

---

## Gaps & Limitations

{gaps}

---

## Verification Notes

{verification_notes}

---

## Citations

{citations}

---

*Report generated by Minerva v0.10.0 on {timestamp}*
"""


class DecomposeStageImpl(IPipelineStage):
    """Decompose query into sub-questions using local LLM."""

    name = "decompose"

    def __init__(self, llm_client, max_sub_questions: int = 5):
        self.llm = llm_client
        self.max_sub = max_sub_questions

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        try:
            response = await self.llm.generate(
                system="You decompose research questions into specific sub-questions.",
                prompt=DECOMPOSE_PROMPT.format(query=ctx.query),
                temperature=0.3,
                max_tokens=500,
            )
            ctx.sub_questions = [
                q.strip("- *").strip()
                for q in response.strip().split("\n")
                if q.strip() and len(q.strip()) > 5
            ][:self.max_sub]
        except Exception:
            ctx.sub_questions = [ctx.query]
        return ctx


class MultiSourceSearchStageImpl(IPipelineStage):
    """Parallel search across multiple backends."""

    name = "search"

    def __init__(self, search_engine, backends: list[str], max_results: int = 25):
        self.search_engine = search_engine
        self.backends = backends
        self.max_results = max_results

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        queries = ctx.sub_questions if ctx.sub_questions else [ctx.query]
        # Parallel search across primary + all sub-questions
        tasks = [
            self.search_engine.search(
                q, backends=self.backends,
                max_results=self.max_results if i == 0 else 5
            )
            for i, q in enumerate(queries)
        ]
        gathered = await asyncio.gather(*tasks, return_exceptions=True)
        results: list = []
        for r in gathered:
            if isinstance(r, list):
                results.extend(r)
            elif isinstance(r, Exception):
                pass  # Individual query failures are non-fatal

        # Deduplicate
        seen: set = set()
        deduped = []
        for r in results:
            if r.url not in seen:
                seen.add(r.url)
                deduped.append(r)
        ctx.search_results = [{
            "title": r.title, "url": r.url, "snippet": r.snippet,
            "source": r.source, "published_date": r.published_date,
            "rank_score": r.rank_score,
        } for r in deduped[:self.max_results]]
        return ctx


class EntityExtractionStageImpl(IPipelineStage):
    """Extract entities using spaCy NLP + LLM fallback with language routing."""

    name = "entity_extraction"

    def __init__(self, nlp_pipeline, llm_client, knowledge_store=None, nlp_zh=None):
        self.nlp = nlp_pipeline  # spaCy Language (English)
        self.nlp_zh = nlp_zh      # spaCy Language (Chinese)
        self.llm = llm_client
        self.kb = knowledge_store

    def _detect_language(self, text: str) -> str:
        """Simple language detection based on character set."""
        zh_chars = sum(1 for c in text if '一' <= c <= '鿿')
        return "zh" if zh_chars > len(text) * 0.05 else "en"

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        entities = []
        if self.nlp is None:
            ctx.entities = []
            return ctx
        for result in ctx.search_results[:10]:
            text = result.get("snippet", "")
            if not text:
                continue
            lang = self._detect_language(text)
            nlp = self.nlp_zh if lang == "zh" and self.nlp_zh else self.nlp
            doc = nlp(text[:1000])
            for ent in doc.ents:
                if ent.label_ in ("ORG", "PERSON", "GPE", "PRODUCT", "WORK_OF_ART"):
                    eid = f"ent-{len(entities)}-{ent.label_}"
                    entity = Entity(
                        id=eid, type=spacy_to_entity_type(ent.label_),
                        name=ent.text,
                        source_ids=[result.get("url", "")],
                        confidence="MEDIUM",
                    )
                    entities.append(entity)
                    if self.kb:
                        with contextlib.suppress(Exception):
                            await self.kb.upsert_entity(entity)
        ctx.entities = [{"id": e.id, "type": e.type, "name": e.name, "confidence": e.confidence} for e in entities]
        return ctx


class DeepReadStageImpl(IPipelineStage):
    """Extract full content and cross-analyze with LLM.

    Uses sliding window: top 5 sources get full extraction (3000 chars each),
    remaining get summary-only (title + URL + 200-char snippet). This avoids
    wasting the 8K token budget on already-read sources (MiroThinker K=5 pattern).
    """

    name = "deep_read"

    def __init__(self, content_extractor, llm_client, top_n: int = 15, full_slot_count: int = 5):
        self.extractor = content_extractor
        self.llm = llm_client
        self.top_n = top_n
        self._full_slot_count = full_slot_count

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        import structlog
        logger = structlog.get_logger(__name__)
        logger.info("deep_read_start", sources=min(self.top_n, len(ctx.search_results)))

        top_results = ctx.search_results[:self.top_n]
        documents = []
        # Sliding window: full extraction for top 5, summary for rest
        full_slots = min(self._full_slot_count, len(top_results))

        # Parallel content extraction for top-N (avoids 10-15s serial latency)
        async def _extract(idx, r):
            url = r.get("url", "")
            if not url:
                return idx, None
            try:
                content = await self.extractor.extract_content(url)
                return idx, content
            except Exception:
                return idx, None

        extract_tasks = [_extract(i, r) for i, r in enumerate(top_results[:full_slots])]
        gathered = await asyncio.gather(*extract_tasks, return_exceptions=True)
        extracted: dict[int, str | None] = {}
        for item in gathered:
            if isinstance(item, tuple) and len(item) == 2:
                extracted[item[0]] = item[1]

        for i, r in enumerate(top_results):
            url = r.get("url", "")
            if not url:
                continue
            if i < full_slots:
                content = extracted.get(i)
                if content:
                    documents.append(f"## {r.get('title', 'Untitled')}\nSource: {url}\n\n{content[:3000]}\n")
            else:
                snippet = r.get("snippet", "")[:200]
                documents.append(f"## {r.get('title', 'Untitled')}\nSource: {url}\n\n{snippet}\n")

        if not documents:
            ctx.extracted_content = []
            return ctx

        docs_text = "\n---\n".join(documents)
        try:
            analysis = await self.llm.generate(
                system="You analyze multiple documents and identify claims, consensus, contradictions, and gaps.",
                prompt=DEEP_READ_PROMPT.format(query=ctx.query, documents=docs_text[:8000]),
                temperature=0.3,
                max_tokens=2000,
            )
        except Exception:
            analysis = "Deep read analysis unavailable."

        ctx.extracted_content = [d[:500] for d in documents]
        ctx.contradictions = ctx.contradictions or []
        ctx.contradictions.append({"analysis": analysis})

        # Step verification after deep read (MiroThinker Local Verifier pattern)
        try:
            from minerva.pipeline.verifier import verify_step
            result = await verify_step(self.llm, ctx, "deep_read")
            if result.get("status") == "warning" and result.get("issue"):
                logger.warning("step_verify_warning", stage="deep_read", issue=result["issue"])
        except Exception:
            logger.debug("stage_fallback", stage=getattr(self, "name", "?"))
            pass

        logger.info("deep_read_complete", docs=len(documents), analysis_len=len(analysis))
        return ctx


class CrossAnalyzeStageImpl(IPipelineStage):
    """Deep reasoning analysis on extracted content."""

    name = "cross_analyze"

    def __init__(self, llm_client):
        self.llm = llm_client

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        analysis = ""
        for c in (ctx.contradictions or []):
            analysis += c.get("analysis", "") + "\n"

        if not analysis.strip():
            ctx.relations = []
            return ctx

        try:
            reasoning = await self.llm.generate(
                system="You perform deep reasoning on research findings.",
                prompt=CROSS_ANALYZE_PROMPT.format(query=ctx.query, analysis=analysis[:4000]),
                temperature=0.5,
                max_tokens=1500,
            )
        except Exception:
            reasoning = "Cross-analysis unavailable."

        ctx.relations = ctx.relations or []
        ctx.relations.append({"reasoning": reasoning})
        return ctx


class QualityGateStageImpl(IPipelineStage):
    """Verify research quality and assign a quality score."""

    name = "quality_gate"

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        failures = []
        score = 100

        # Source count
        if not ctx.search_results:
            failures.append("No search results found")
            score = 0
        elif len(ctx.search_results) < 3:
            failures.append("Insufficient sources (<3)")
            score -= 30
        elif len(ctx.search_results) < 5:
            score -= 10

        # Entity extraction
        if not ctx.entities:
            score -= 10  # No entities found — but not a failure

        # Contradiction depth
        has_analysis = any(
            c.get("analysis") and len(c.get("analysis", "")) > 50
            for c in (ctx.contradictions or [])
        )
        if not has_analysis and ctx.contradictions:
            score -= 10

        # Source diversity
        if ctx.search_results:
            sources = {r.get("source", "") for r in ctx.search_results}
            if len(sources) == 1:
                score -= 15  # Only one backend

        ctx.relations = ctx.relations or []
        ctx.relations.append({
            "quality_score": max(0, score),
            "quality_gate_checks": {
                "source_count": len(ctx.search_results),
                "entity_count": len(ctx.entities),
                "contradiction_analysis": has_analysis,
            },
            "failures": failures,
        })

        if failures:
            raise QualityGateFailure(f"[score:{score}] {'; '.join(failures)}")

        return ctx


class OutputStageImpl(IPipelineStage):
    """Generate final report and write to disk.

    Shared base for L0-L4 output stages. ExtendedOutputStageImpl inherits for L4.
    """

    name = "output"

    # Source → confidence level mapping for evidence tables
    _SOURCE_CONFIDENCE = {
        "scholar": "HIGH", "arxiv": "HIGH", "exa": "MEDIUM-HIGH",
        "metaso": "MEDIUM", "ddg": "MEDIUM", "brave": "MEDIUM",
        "searxng": "MEDIUM", "web": "MEDIUM",
    }

    def __init__(self, llm_client=None, knowledge_store=None, report_dir: str = "~/knowledge/reports"):
        self.llm = llm_client
        self.kb = knowledge_store
        self.report_dir = Path(report_dir).expanduser()

    # -- Shared helpers --------------------------------------------------

    def _get_quality_score(self, ctx: ResearchContext) -> str:
        for r in (ctx.relations or []):
            if "quality_score" in r:
                return str(r["quality_score"])
        return "N/A"

    def _build_filename(self, ctx: ResearchContext) -> tuple[str, str]:
        ts = time.strftime("%Y%m%d-%H%M%S")
        slug = ctx.query[:40].replace(" ", "-").lower()
        return ts, slug

    def _source_conf(self, src: str) -> str:
        return self._SOURCE_CONFIDENCE.get(src, "MEDIUM")

    def _build_findings(self, ctx: ResearchContext, n: int = 8, max_snippet: int = 200) -> str:
        lines = []
        for i, r in enumerate(ctx.search_results[:n]):
            lines.append(f"{i+1}. **{r.get('title', 'Untitled')}** — {r.get('snippet', '')[:max_snippet]}")
        return "\n".join(lines) if lines else "No findings available."

    def _build_evidence_rows(self, ctx: ResearchContext, n: int = 8) -> str:
        rows = []
        for r in ctx.search_results[:n]:
            src = r.get("source", "web")
            conf = self._source_conf(src)
            rows.append(f"| {r.get('title', 'Untitled')[:50]} | {r.get('url', '')[:50]} | {conf} |")
        return "\n".join(rows)

    def _build_contradictions(self, ctx: ResearchContext) -> str:
        parts = []
        for c in (ctx.contradictions or []):
            analysis = c.get("analysis", "")
            if analysis and len(analysis) > 50:
                parts.append(analysis[:500])
        if parts:
            return "\n".join(parts)
        sources_list = ", ".join({r.get("source", "web") for r in ctx.search_results[:5]})
        return (
            f"No direct contradictions found across {len(ctx.search_results)} sources "
            f"from {sources_list}. Cross-source consensus suggests reliable findings."
        )

    def _build_gaps(self, ctx: ResearchContext) -> str:
        gaps = ""
        source_types = {r.get("source", "web") for r in ctx.search_results}
        if "scholar" not in source_types and "arxiv" not in source_types:
            gaps += "- Academic sources (Semantic Scholar / arXiv) not represented in results.\n"
        if len(ctx.search_results) < 5:
            gaps += f"- Limited source count ({len(ctx.search_results)}). Consider re-running at higher level.\n"
        return gaps or f"Coverage across {len(source_types)} source types. Consider deeper analysis for specific sub-topics."

    def _build_citations(self, ctx: ResearchContext, n: int = 10) -> str:
        lines = []
        for i, r in enumerate(ctx.search_results[:n]):
            lines.append(f"{i+1}. [{r.get('title', 'Untitled')[:80]}]({r.get('url', '')})")
        return "\n".join(lines)

    def _generate_tldr(self, ctx: ResearchContext) -> str:
        """Generate a 2-3 sentence TL;DR summary from research context."""
        src_count = len(ctx.search_results)
        entity_count = len(ctx.entities)
        contradictions_found = any(
            c.get("analysis") and len(c.get("analysis", "")) > 50
            for c in (ctx.contradictions or [])
        )
        top_sources = ", ".join(
            r.get("title", "Untitled")[:40]
            for r in ctx.search_results[:3]
        )
        parts = [
            f"Research analyzed {src_count} sources",
            f"extracted {entity_count} entities" if entity_count else "",
            f"found contradictions: {'yes' if contradictions_found else 'no significant'}" if src_count >= 3 else "",
        ]
        core = ". ".join(p for p in parts if p) + "."
        return f"{core} Key sources: {top_sources}."

    async def _write_bilingual(self, ctx: ResearchContext, report: str, ts: str, slug: str) -> str | None:
        """Write EN report and best-effort ZH translation. Returns zh_path or None."""
        quality_score = self._get_quality_score(ctx)
        en_path = self.report_dir / f"{ts}_{slug}_EN.md"
        en_header = f"> **Quality Score: {quality_score}/100** | Level: {ctx.level.value} | Sources: {len(ctx.search_results)}\n\n"
        en_path.write_text(en_header + report)

        if not self.llm or len(report) <= 100:
            return None
        try:
            zh_output = await self.llm.generate(
                system="You translate research reports from English to Chinese. Preserve markdown formatting, citations, tables, and structure exactly. Only translate the text content.",
                prompt=f"Translate this research report to Chinese. Keep all markdown formatting, URLs, and table structures unchanged:\n\n{report[:6000]}",
                temperature=0.2,
                max_tokens=4096,
            )
            zh_path = self.report_dir / f"{ts}_{slug}_ZH.md"
            zh_header = f"> **质量评分: {quality_score}/100** | 级别: {ctx.level.value} | 来源: {len(ctx.search_results)}\n\n"
            zh_path.write_text(zh_header + zh_output)
            return str(zh_path)
        except Exception:
            return None

    # -- Main execute ----------------------------------------------------

    def _build_process_log(self, ctx: ResearchContext) -> str:
        """Generate a research process summary showing how the analysis was conducted."""
        lines = []
        stages = [
            ("Decompose", f"Query decomposed into {len(ctx.sub_questions)} sub-questions" if ctx.sub_questions else "Query analyzed as single question"),
            ("Search", f"Found {len(ctx.search_results)} sources across {len({r.get('source','web') for r in ctx.search_results})} backends"),
            ("Entity Extraction", f"Extracted {len(ctx.entities)} entities from search results" if ctx.entities else "No entities extracted"),
            ("Deep Read", "Cross-analyzed top sources for claims, consensus, and contradictions"),
            ("Cross Analysis", f"Reasoning performed on {len(ctx.contradictions or [])} contradiction points"),
            ("Quality Gate", f"Quality score: {self._get_quality_score(ctx)}/100"),
        ]
        for name, detail in stages:
            lines.append(f"1. **{name}**: {detail}")
        for name, elapsed in ctx.stage_timings.items():
            pass  # Available but not shown in process log
        return "\n".join(lines)

    def _build_sub_questions_analysis(self, ctx: ResearchContext) -> str:
        if not ctx.sub_questions:
            return "No sub-questions were generated — the query was analyzed as a single question."
        lines = ["The research was structured around these sub-questions:"]
        for i, q in enumerate(ctx.sub_questions[:10]):
            srcs = sum(1 for r in ctx.search_results if any(
                w.lower() in r.get("title", "").lower() + r.get("snippet", "").lower()
                for w in q.lower().split()[:3]
            ))
            lines.append(f"{i+1}. **{q}** — {srcs} relevant sources found")
        return "\n".join(lines)

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        import structlog, time as _time
        logger = structlog.get_logger(__name__)
        is_quick = ctx.level.value == "L0"
        logger.info("output_start", sources=len(ctx.search_results), entities=len(ctx.entities), quick=is_quick)

        self.report_dir.mkdir(parents=True, exist_ok=True)

        tldr = self._generate_tldr(ctx)
        process_log = self._build_process_log(ctx)
        sub_questions_analysis = self._build_sub_questions_analysis(ctx)
        quality_score = self._get_quality_score(ctx)

        # Build evidence rows with numbering for traceability
        evidence_rows = ""
        source_confidence = self._SOURCE_CONFIDENCE
        for i, r in enumerate(ctx.search_results[:8]):
            src = r.get("source", "web")
            conf = source_confidence.get(src, "MEDIUM")
            supports = "✓" if r.get("rank_score", 0) > 0.3 else "~"
            evidence_rows += f"| {i+1} | {r.get('title', 'Untitled')[:50]} | {r.get('url', '')[:40]} | {conf} | {supports} |\n"

        # Global verification
        verification = {"verified": True, "issues": []}
        verification_notes = "Verification skipped (available at L2+)."
        if self.llm and ctx.level.value not in ("L0", "L1"):
            try:
                from minerva.pipeline.verifier import verify_report
                temp_report = REPORT_TEMPLATE.format(
                    query=ctx.query, quality_score=quality_score, level=ctx.level.value,
                    source_count=len(ctx.search_results), cost=f"{ctx.cost:.2f}",
                    process_log=process_log, findings=self._build_findings(ctx),
                    evidence_rows=evidence_rows, contradictions=self._build_contradictions(ctx),
                    gaps=self._build_gaps(ctx), sub_questions_analysis=sub_questions_analysis,
                    verification_notes="Verification in progress...", citations=self._build_citations(ctx),
                    timestamp=_time.strftime("%Y-%m-%d %H:%M:%S"), tldr=tldr,
                )
                verification = await verify_report(self.llm, temp_report, ctx.search_results)
                if verification.get("issues"):
                    logger.warning("global_verify_issues", count=len(verification["issues"]))
            except Exception:
                logger.debug("stage_fallback", stage=getattr(self, "name", "?"))
                pass

        if verification.get("issues"):
            notes = []
            for issue in verification["issues"]:
                notes.append(f"- ⚠️ [{issue.get('issue', '?')}] {issue.get('claim', '')[:100]}: {issue.get('detail', '')[:200]}")
            verification_notes = "\n".join(notes)
        elif not verification["verified"]:
            verification_notes = "Verification could not be completed."
        else:
            verification_notes = "All verifiable claims are supported by at least one source."

        # Paradigm information for report header
        paradigm_name = "Auto"
        paradigm_stages = "Search → Analyze → Report"
        try:
            from minerva.paradigm.types import PARADIGMS
            from minerva.paradigm.router import classify_paradigm
            # Re-classify for report metadata (uses rule-based when no LLM)
            pr = await classify_paradigm(self.llm, ctx.query)
            pdef = PARADIGMS.get(pr.paradigm)
            if pdef:
                paradigm_name = pdef.name
                paradigm_stages = " → ".join(pdef.stages)
        except Exception:
            pass

        report = REPORT_TEMPLATE.format(
            query=ctx.query,
            paradigm_name=paradigm_name,
            paradigm_stages=paradigm_stages,
            quality_score=quality_score,
            level=ctx.level.value,
            source_count=len(ctx.search_results),
            cost=f"{ctx.cost:.2f}",
            process_log=process_log,
            findings=self._build_findings(ctx),
            evidence_rows=evidence_rows,
            contradictions=self._build_contradictions(ctx),
            gaps=self._build_gaps(ctx),
            sub_questions_analysis=sub_questions_analysis,
            verification_notes=verification_notes,
            citations=self._build_citations(ctx),
            timestamp=_time.strftime("%Y-%m-%d %H:%M:%S"),
            tldr=tldr,
        )

        ts, slug = self._build_filename(ctx)
        # L0 skips ZH translation for speed
        zh_path = None if is_quick else await self._write_bilingual(ctx, report, ts, slug)

        ctx.report = report
        ctx.report_path = str(self.report_dir / f"{ts}_{slug}_EN.md")
        if zh_path:
            ctx.relations = ctx.relations or []
            ctx.relations.append({"zh_report_path": zh_path})
        ctx.relations = ctx.relations or []
        ctx.relations.append({"verification": verification})

        if self.llm:
            try:
                from minerva.creative.notebooklm_adapter import generate_audio_overview
                report_path = str(self.report_dir / f"{ts}_{slug}_EN.md")
                audio_result = await asyncio.to_thread(generate_audio_overview, report_path)
                if audio_result.get("status") not in ("unavailable", "error"):
                    ctx.relations.append({"audio_overview": audio_result})
                logger.info("notebooklm_audio", status=audio_result.get("status", "unknown"))
            except Exception:
                logger.debug("stage_fallback", stage=getattr(self, "name", "?"))
                pass

        # Auto-index entities into LanceDB for semantic search
        if ctx.entities:
            try:
                from minerva.knowledge.store import LanceDBVectorStore, Entity
                vs = LanceDBVectorStore()
                entities = [Entity(id=e["id"], type=e.get("type","Concept"), name=e["name"],
                                   confidence=e.get("confidence","MEDIUM"), properties=e.get("properties", {}))
                            for e in ctx.entities if isinstance(e, dict)]
                await vs.index_entities(entities, mode="overwrite")
                logger.info("vector_index", entities=len(entities))
            except Exception:
                logger.debug("stage_fallback", stage=getattr(self, "name", "?"))
                pass

        logger.info("output_complete", report_len=len(report), verified=verification["verified"])
        return ctx


# _spacy_to_entity_type moved to minerva.shared (shared/spacy_to_entity_type)


# ============================================================
# L3/L4 Specific Stages
# ============================================================

COUNTER_ARGUMENT_PROMPT = """Given this research on: {query}

{findings}

You are playing devil's advocate. Identify:
1. The strongest counter-arguments to the main conclusions
2. Alternative interpretations of the evidence
3. Weaknesses in methodology or assumptions
4. Missing perspectives or stakeholders
5. Overlooked risks or downsides

Be specific and cite sources where possible. Output in markdown."""

MULTI_MODEL_PROMPT = """Given this research analysis on: {query}

{analysis}

You are a panel of expert reviewers. Provide:
1. Voting on each major conclusion (AGREE/DISAGREE/NEUTRAL with justification)
2. Confidence score for each conclusion (HIGH/MEDIUM/LOW)
3. Areas where models disagree and why
4. Recommended follow-up research questions
5. Final consensus summary

Output in structured markdown."""


class CounterArgumentStageImpl(IPipelineStage):
    """Generate counter-arguments and alternative perspectives. (L3+)"""

    name = "counter_argument"

    def __init__(self, llm_client):
        self.llm = llm_client

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        findings = ""
        for c in (ctx.contradictions or []):
            findings += c.get("analysis", "") + "\n"
        if not findings.strip():
            findings = "\n".join(
                f"- {r.get('title', '')}: {r.get('snippet', '')[:200]}"
                for r in ctx.search_results[:5]
            )

        try:
            response = await self.llm.generate(
                system="You are a critical thinker who identifies weaknesses and alternative perspectives in research.",
                prompt=COUNTER_ARGUMENT_PROMPT.format(query=ctx.query, findings=findings[:4000]),
                temperature=0.5,
                max_tokens=1500,
            )
        except Exception:
            response = "Counter-argument analysis unavailable."

        ctx.relations = ctx.relations or []
        ctx.relations.append({"counter_argument": response})
        return ctx


class MultiModelVotingStageImpl(IPipelineStage):
    """Multi-model voting on conclusions. (L4)"""

    name = "multi_model_voting"

    def __init__(self, llm_client):
        self.llm = llm_client

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        analysis = ""
        for r in (ctx.relations or []):
            for v in r.values():
                analysis += str(v)[:2000] + "\n"

        if not analysis.strip():
            ctx.relations = ctx.relations or []
            ctx.relations.append({"voting": "Insufficient data for multi-model voting."})
            return ctx

        try:
            response = await self.llm.generate(
                system="You are a panel of expert reviewers evaluating research conclusions.",
                prompt=MULTI_MODEL_PROMPT.format(query=ctx.query, analysis=analysis[:4000]),
                temperature=0.4,
                max_tokens=1500,
            )
        except Exception:
            response = "Multi-model voting unavailable."

        ctx.relations = ctx.relations or []
        ctx.relations.append({"voting": response})
        return ctx


class ExtendedOutputStageImpl(OutputStageImpl):
    """Extended report for L4 with full analysis depth — inherits shared helpers."""

    name = "extended_output"

    async def execute(self, ctx: ResearchContext) -> ResearchContext:
        self.report_dir.mkdir(parents=True, exist_ok=True)

        summary = f"# Extended Research Report: {ctx.query}\n\n"
        summary += f"**Level:** {ctx.level.value} | "
        summary += f"**Sources:** {len(ctx.search_results)} | "
        summary += f"**Entities:** {len(ctx.entities)} | "
        summary += f"**Cost:** ${ctx.cost:.2f}\n\n"

        summary += "## Key Findings\n\n"
        summary += self._build_findings(ctx, n=12, max_snippet=300) + "\n"

        summary += "## Evidence Matrix\n\n"
        summary += "| Claim | Source | Confidence |\n"
        summary += "|-------|--------|------------|\n"
        summary += self._build_evidence_rows(ctx, n=12) + "\n"

        summary += "\n## Counter-Arguments\n\n"
        ca = next((r.get("counter_argument", "") for r in (ctx.relations or []) if r.get("counter_argument")), "")
        summary += (ca[:2000] if ca else "No counter-arguments generated.") + "\n"

        summary += "\n## Multi-Model Voting\n\n"
        v = next((r.get("voting", "") for r in (ctx.relations or []) if r.get("voting")), "")
        summary += (v[:2000] if v else "Multi-model voting not performed.") + "\n"

        summary += "\n## Cross-Analysis\n\n"
        first_analysis = next((c.get("analysis", "") for c in (ctx.contradictions or []) if c.get("analysis")), "")
        summary += first_analysis[:1500] + "\n" if first_analysis else "No cross-analysis available.\n"

        summary += "\n## Full Citation List\n\n"
        summary += self._build_citations(ctx, n=15) + "\n"

        ts, slug = self._build_filename(ctx)
        path = self.report_dir / f"{ts}_{slug}_L4.md"
        path.write_text(summary)

        ctx.report = summary
        ctx.report_path = str(path)
        return ctx
